### ISSUE TITLE
General enhancements ideas

### ISSUE THREAD

**Issue by jonbragado** [alicevision/meshroom#547]
1. Streamline node interface: Nodes are fantastic but the interface on them is made for engineers. there are too many things visible there, almost every parameter is exposed with names that dont tell the user the correct usage about the effect of modifying that parameter. Tooltips in plain language would be very useful.
2. Navigation & Viewport: The viewport should behave like the rest of the 3d DCCA standard apps out there, with the same visual controls and keyboard keys.
3.- View through camera: Very useful to be albe to select a camera and see through it to see the geo matching that pictures lineup. We should also be albe to see the corresponding point overlaid on the image and the geo.

**Comment by natowi** [comment]
1. This is why we have the "Advanced Settings" mode since 2019.1. (In the node attributes, (...) button)
With the next release, there will be an [improved Add Node](https://github.com/alicevision/meshroom/pull/248) menu. In the future it will provide details (and maybe an example image) for each node. In the meantime you can find details on the nodes in the manual (wip).
Here are some other improvements for the Graph view (nodes) [#269] 
2. From my experience each 3d software behaves slightly different. But it would be a good idea to 
- [ ] enable the user to define the navigation shortcuts in a preferences menu
3. Good idea.
- [ ] View through camera
- [ ] show images as 2d planes (small at camera origin, and proportional larger on the view path [#358]
4. 
- [ ] A General preferences menu would require some configurable preferences. This could be:
- [ ] Select path [#472](https://github.com/alicevision/meshroom/issues/472)
- [ ] configure keyboard shortcuts
- [ ] System resource usage
- [ ] render farm settings
Related:
- [ ] Project Manager (configure and store projects and settings) [#360](https://github.com/alicevision/meshroom/issues/360)
- [ ] Manage node graphs [#361]

**Comment by MightyBOBcnc** [comment]
#2 (user-configurable navigation) would be especially welcome.  Trackball/gizmo navigation is, frankly, awful and is not how viewport navigation functions in professional modeling/texturing software. (e.g. Maya, 3DS Max, Mudbox, Substance Painter, Marmoset Toolbag, Quixel Suite, 3D-Coat, Blender, even Sketchfab viewer and so on.)

While, as you note, there are variations in the viewport navigation controls the general commonality between most 3D software is that:
* One mouse button (often the left mouse button, and often in combination with a second button, e.g. Alt+Left Mouse) will be used with the left/right movement of the mouse to rotate the viewport camera around its own local "vertical" axis (the green axis in Meshroom) and will also be used with the forward/backward movement of the mouse to rotate the viewport camera around its own local "side" axis (the red axis in Meshroom).
* One mouse button (often the right mouse button or Alt+Right Mouse) will be used with either the left/right or forward/backward movement of the mouse to translate the camera forward/backward along its own local look/aim axis (the blue axis in Meshroom).  [Note: Sometimes, like in Maya, both mouse movement axes are available at the same time so you can use whichever floats your boat.]
** The mouse scroll wheel also translates the camera on its look/aim axis.
* One mouse button (often middle clicking the scroll wheel or Alt+Mouse Middle) will be used with the left/right movement of the mouse to translate the viewport camera left/right on its local "side" (red) axis and will also be used with the forward/backward movement of the mouse to translate the viewport camera up/down on its own local vertical (green) axis.

Meshroom camera for axis color reference: https://i.imgur.com/KO05y0p.png

**Comment by jonbragado** [comment]
we can only read .JPG files? It should be standard that any most commonly used known image formats in computer graphics are taken for granted a new software breaking in the CG arena is able to read. 
Hopefully, this gets added as a priority, image conversion shouldn't be necessary. In fact, original RAW files or .DNG files should still be welcome (computing expense at the cost of the user).

**Comment by natowi** [comment]
@jonbragado no, see [Supported-image-formats](https://github.com/alicevision/meshroom/wiki/Supported-image-formats)

**Comment by jonbragado** [comment]
Sorry about that I never had any luck loading .png, or tiff files myself.

**Comment by natowi** [comment]
@jonbragado can you create a new issue and you share a problematic image?
